/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MorelloBello2.src.gui_package;

import MorelloBello2.src.data_package.Libri;
import MorelloBello2.src.data_package.Utenti;

/**
 *
 * @author matteo
 */
public class Visualizza_libro extends javax.swing.JPanel {

    /**
     * Creates new form Visualizza_libro
     */
    public Visualizza_libro(Utenti utente,Libri libro) {
        initComponents();
        modifica.setVisible(false);
        
        String autori="";
        String generi="";
        if(utente.isAdmin()){
            modifica.setVisible(true);
        }
        titolo.setText(libro.getTitle());
        
        casa_produttrice.setText(libro.getEditor());
        descrizione.setText(libro.getDescription());
        prezzo.setText(Float.toString(libro.getPrice()));
        punti.setText(Integer.toString(libro.getNumberofpoints()));
        
        for(int i=0;i<libro.getAuthor().size();i++){
            autori=autori+libro.getAuthor().get(i)+",";
        }
        autore.setText(autori);
        
        for(int i=0;i<libro.getGenre().size();i++){
            generi=generi+libro.getGenre().get(i)+",";
        }
        genere.setText(generi);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titolo = new javax.swing.JLabel();
        autore = new javax.swing.JLabel();
        casa_produttrice = new javax.swing.JLabel();
        genere = new javax.swing.JLabel();
        prezzo = new javax.swing.JLabel();
        punti = new javax.swing.JLabel();
        descrizione = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        ordina = new javax.swing.JButton();
        modifica = new javax.swing.JButton();

        titolo.setText("jLabel1");

        autore.setText("jLabel2");

        casa_produttrice.setText("jLabel3");

        genere.setText("jLabel4");

        prezzo.setText("jLabel5");

        punti.setText("jLabel6");

        descrizione.setText("jLabel7");

        foto.setText("jLabel8");

        ordina.setText("ordina");

        modifica.setText("modifica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(descrizione)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(foto)
                .addGap(177, 177, 177)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prezzo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(punti))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casa_produttrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(genere))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titolo)
                        .addGap(92, 92, 92)
                        .addComponent(autore)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ordina)
                    .addComponent(modifica))
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titolo)
                    .addComponent(autore)
                    .addComponent(foto)
                    .addComponent(ordina))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casa_produttrice)
                    .addComponent(genere)
                    .addComponent(modifica))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prezzo)
                    .addComponent(punti))
                .addGap(105, 105, 105)
                .addComponent(descrizione)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autore;
    private javax.swing.JLabel casa_produttrice;
    private javax.swing.JLabel descrizione;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel genere;
    private javax.swing.JButton modifica;
    private javax.swing.JButton ordina;
    private javax.swing.JLabel prezzo;
    private javax.swing.JLabel punti;
    private javax.swing.JLabel titolo;
    // End of variables declaration//GEN-END:variables
}
