/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_package;

import data_package.Utenti;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lorenzo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        PaginaPrincipale = new javax.swing.JMenu();
        PaginaProfilo = new javax.swing.JMenu();
        PaginaOrdini = new javax.swing.JMenu();
        Carrello = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PaginaPrincipale.setText("Pagina Principale");
        PaginaPrincipale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaPrincipaleActionPerformed(evt);
            }
        });
        jMenuBar1.add(PaginaPrincipale);

        PaginaProfilo.setText("Utente");
        PaginaProfilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaProfiloActionPerformed(evt);
            }
        });
        jMenuBar1.add(PaginaProfilo);

        PaginaOrdini.setText("Ordini");
        PaginaOrdini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaOrdiniActionPerformed(evt);
            }
        });
        jMenuBar1.add(PaginaOrdini);

        Carrello.setText("Carrello");
        jMenuBar1.add(Carrello);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaginaPrincipaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaPrincipaleActionPerformed
        // TODO add your handling code here:
        main_page pagina = null;
        try {
            pagina = new main_page();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setSize(900, 900);
    }//GEN-LAST:event_PaginaPrincipaleActionPerformed

    private void PaginaProfiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaProfiloActionPerformed
        // TODO add your handling code here:
        visualizza_utente pagina = new visualizza_utente(Utenti.utente, this);
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setSize(900, 900);
    }//GEN-LAST:event_PaginaProfiloActionPerformed

    private void PaginaOrdiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaOrdiniActionPerformed
        // TODO add your handling code here:
        Lista_ordini pagina = null;
        try {
            pagina = new Lista_ordini(Utenti.utente);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setSize(900, 900);
    }//GEN-LAST:event_PaginaOrdiniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Carrello;
    private javax.swing.JMenu PaginaOrdini;
    private javax.swing.JMenu PaginaPrincipale;
    private javax.swing.JMenu PaginaProfilo;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
