/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_package;
import gui_package.Lista_ordini_frame;
import data_package.Libri;
import data_package.Utenti;
import data_package.database;
import static java.lang.Math.random;
import java.util.ArrayList;
import java.util.Comparator;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author Lorenzo
 */
public class Risultati_Ricerca extends javax.swing.JFrame  {
    private ResultSet rs;
    private PreparedStatement pstmt;
    private final Connection conn;
    private final Statement stmt;
	
    /**
     * Creates new form Risultati_Ricerca
     */
    public Risultati_Ricerca(String research) throws SQLException {
        initComponents();
         conn= database.connection();
         stmt = conn.createStatement();
         ArrayList<Libri> risultati = new ArrayList<Libri>();
         rs = stmt.executeQuery("SELECT libri.ISBN from libri, autori, autori_libri WHERE libri.ISBN='" + research + "' OR autori.nome='" + research+
                 "' OR libri.titolo='" + research + "' AND (libri.ISBN=autori_libri.ISBN AND autori.codice=autori_libri.codice)");
         
         while(rs.next()){
             Libri a = new Libri(rs.getString("ISBN"));
             risultati.add(a);
         }
         
         DefaultListModel model = new DefaultListModel();
         for(Libri a:risultati){
             model.addElement("" + a.getTitle() + " " + a.getAuthor() + " " +a.getEditor() +  " " + a.getISBN() + " " + a.getPrice());
         }
         
         Lista_Risultati.setModel(model);
         
         DefaultComboBoxModel mode = new DefaultComboBoxModel();
         for(Libri a:risultati){
             mode.addElement(a.getISBN());
         }
         Selezione_Libro.setModel(mode);
         
         
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Risultati = new javax.swing.JList<>();
        Visualizza_Libro = new javax.swing.JButton();
        Selezione_Libro = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        PaginaPrincipale = new javax.swing.JMenu();
        PaginaProfilo = new javax.swing.JMenu();
        PaginaOrdini = new javax.swing.JMenu();
        Carrello = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lista_Risultati.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Lista_Risultati);

        Visualizza_Libro.setText("Visualizza Libro");
        Visualizza_Libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Visualizza_LibroActionPerformed(evt);
            }
        });

        Selezione_Libro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        PaginaPrincipale.setText("Pagina Principale");
        PaginaPrincipale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaPrincipaleActionPerformed(evt);
            }
        });
        jMenuBar1.add(PaginaPrincipale);

        PaginaProfilo.setText("Utente");
        PaginaProfilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaProfiloActionPerformed(evt);
            }
        });
        jMenuBar1.add(PaginaProfilo);

        PaginaOrdini.setText("Ordini");
        PaginaOrdini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaginaOrdiniActionPerformed(evt);
            }
        });
        jMenuBar1.add(PaginaOrdini);

        Carrello.setText("Carrello");
        jMenuBar1.add(Carrello);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Selezione_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Visualizza_Libro))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Visualizza_Libro)
                    .addComponent(Selezione_Libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Visualizza_LibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Visualizza_LibroActionPerformed
        try {
            // TODO add your handling code here:
            visualizza_libro_frame libro = new visualizza_libro_frame(Utenti.utente, new Libri(Selezione_Libro.getSelectedItem().toString()));
        } catch (SQLException ex) {
            Logger.getLogger(Risultati_Ricerca.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Visualizza_LibroActionPerformed

    private void PaginaPrincipaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaPrincipaleActionPerformed
        // TODO add your handling code here:
        main_page pagina = null;
        try {
            pagina = new main_page();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setSize(900, 900);
    }//GEN-LAST:event_PaginaPrincipaleActionPerformed

    private void PaginaProfiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaProfiloActionPerformed
        // TODO add your handling code here:
        visualizza_utente_frame pagina = new visualizza_utente_frame(Utenti.utente);
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setSize(900, 900);
    }//GEN-LAST:event_PaginaProfiloActionPerformed

    private void PaginaOrdiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaginaOrdiniActionPerformed
        // TODO add your handling code here:
        Lista_ordini_frame pagina = null;
        try {
            pagina = new Lista_ordini_frame(Utenti.utente);
        } catch (SQLException ex) {
            Logger.getLogger(Risultati_Ricerca.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        pagina.setVisible(true);
        pagina.setSize(900, 900);
    }//GEN-LAST:event_PaginaOrdiniActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Risultati_Ricerca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Risultati_Ricerca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Risultati_Ricerca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Risultati_Ricerca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Risultati_Ricerca().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Carrello;
    private javax.swing.JList<String> Lista_Risultati;
    private javax.swing.JMenu PaginaOrdini;
    private javax.swing.JMenu PaginaPrincipale;
    private javax.swing.JMenu PaginaProfilo;
    private javax.swing.JComboBox<String> Selezione_Libro;
    private javax.swing.JButton Visualizza_Libro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
