/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_package;

import data_package.Utenti;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author matteo
 */
public class visualizza_utente extends javax.swing.JPanel {

    /**
     * Creates new form visualizza_utente
     */
    Utenti utente;
    JFrame frame;
    public visualizza_utente(Utenti utente,JFrame frame) {
        this.frame=frame;
        this.utente=utente;
        initComponents();
        nome.setText(utente.getName());
        cognome.setText(utente.getSurname());
        indirizzo.setText(utente.getAddress());
        citta.setText(utente.getCity());
        telefono.setText(utente.getPhone_number());
        email.setText(utente.getEmail());
        password.setText(utente.getPassword());
        codice_carta.setText(Integer.toString(utente.getLibroCard()));
        punti_carta.setText(Integer.toString(utente.getNumberofpoints()));
        data_validazione.setText(utente.getData_emissione().toString());
        cap.setText(Integer.toString(utente.getCAP()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cognome = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        indirizzo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        citta = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        codice_carta = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        punti_carta = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        data_validazione = new javax.swing.JLabel();
        modifica = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cap = new javax.swing.JLabel();

        jLabel1.setText("nome");

        nome.setText("jLabel2");

        jLabel3.setText("cognome");

        cognome.setText("jLabel4");

        jLabel5.setText("indirizzo");

        indirizzo.setText("jLabel6");

        jLabel7.setText("citta");

        citta.setText("jLabel8");

        jLabel9.setText("telefono");

        telefono.setText("jLabel10");

        jLabel11.setText("e-mail");

        email.setText("jLabel12");

        jLabel13.setText("password");

        password.setText("jLabel14");

        jLabel15.setText("carta");

        codice_carta.setText("jLabel16");

        jLabel17.setText("punti_carta");

        punti_carta.setText("jLabel18");

        jLabel19.setText("data_validazione");

        data_validazione.setText("jLabel20");

        modifica.setText("modifica");
        modifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificaMouseClicked(evt);
            }
        });

        jLabel2.setText("CAP");

        cap.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cognome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addComponent(modifica)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome)
                            .addComponent(data_validazione)
                            .addComponent(punti_carta)
                            .addComponent(codice_carta)
                            .addComponent(password)
                            .addComponent(email)
                            .addComponent(telefono)
                            .addComponent(indirizzo)
                            .addComponent(citta)
                            .addComponent(cap))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cognome)
                    .addComponent(modifica))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(indirizzo))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(citta))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(telefono))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(email))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(password))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(codice_carta))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(punti_carta))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(data_validazione))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modificaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificaMouseClicked
        
        try {
            // TODO add your handling code here:
            modifica_utente_frame modifica=new modifica_utente_frame(utente);
        } catch (SQLException ex) {
            Logger.getLogger(visualizza_utente.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(false);
        try {
            main_page main=new main_page();
        } catch (SQLException ex) {
            Logger.getLogger(visualizza_utente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cap;
    private javax.swing.JLabel citta;
    private javax.swing.JLabel codice_carta;
    private javax.swing.JLabel cognome;
    private javax.swing.JLabel data_validazione;
    private javax.swing.JLabel email;
    private javax.swing.JLabel indirizzo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modifica;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel password;
    private javax.swing.JLabel punti_carta;
    private javax.swing.JLabel telefono;
    // End of variables declaration//GEN-END:variables
}
